name: authelia-docker

services:
  authelia:
    image: authelia/authelia:4.39.4@sha256:64b356c30fd817817a4baafb4dbc0f9f8702e46b49e1edb92ff42e19e487b517
    container_name: authelia
    depends_on:
      postgresql:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./config/authelia:/config:ro
      - ${BASE_STACK_DATA_PATH}/authelia:/var/lib/authelia
      - ${BASE_STACK_DATA_PATH}/secrets:/run/authelia-secrets:ro
    environment:
      TZ: ${TZ}
      AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE: /run/authelia-secrets/reset_password_jwt_secret
      AUTHELIA_SESSION_SECRET_FILE: /run/authelia-secrets/session_secret
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: /run/authelia-secrets/storage_encryption_key
      AUTHELIA_STORAGE_POSTGRES_PASSWORD_FILE: /run/authelia-secrets/postgres_password
      AUTHELIA_NOTIFIER_SMTP_ADDRESS: ${AUTHELIA_NOTIFIER_SMTP_ADDRESS:-smtp://smtp-relay:25}
      AUTHELIA_NOTIFIER_SMTP_SENDER: ${AUTHELIA_NOTIFIER_SMTP_SENDER:-noreply@example.com}
    ports: []
    networks:
      - authelia_internal
      - proxy_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://127.0.0.1:9091/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    user: "${AUTHELIA_UID}:${AUTHELIA_GID}"

  postgresql:
    image: docker.io/library/postgres:16.13@sha256:ce5c12ac6952df86affd04ade354cfcb9a0aa1171cd7912e6dbd81578a989a63
    volumes:
      - ${BASE_STACK_DATA_PATH}/postgresql:/var/lib/postgresql/data
      - ${BASE_STACK_DATA_PATH}/secrets:/run/authelia-secrets:ro
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD_FILE: /run/authelia-secrets/postgres_password
    ports: []
    networks:
      - authelia_internal
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: docker.io/library/redis:8@sha256:a019c005570189bb038155c1dfb1a269b59b83f9ceee22fd5f42de205ac19c06
    ports: []
    networks:
      - authelia_internal
    command: ["redis-server", "--save", "", "--appendonly", "no", "--loglevel", "warning"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  authelia_internal:
    internal: true
  proxy_net:
    external: true
    name: network_backend_net
