name: authelia-docker

services:
  authelia:
    image: authelia/authelia:4.39.4@sha256:64b356c30fd817817a4baafb4dbc0f9f8702e46b49e1edb92ff42e19e487b517
    container_name: authelia
    depends_on:
      postgresql:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./config/authelia:/config:ro
      - ${BASE_STACK_DATA_PATH}/authelia:/var/lib/authelia
    environment:
      TZ: ${TZ}
      AUTHELIA_IDENTITY_VALIDATION__RESET_PASSWORD__JWT_SECRET: ${AUTHELIA_IDENTITY_VALIDATION__RESET_PASSWORD__JWT_SECRET}
      AUTHELIA_SESSION__SECRET: ${AUTHELIA_SESSION__SECRET}
      AUTHELIA_STORAGE__ENCRYPTION_KEY: ${AUTHELIA_STORAGE__ENCRYPTION_KEY}
      AUTHELIA_STORAGE__POSTGRES__PASSWORD: ${AUTHELIA_STORAGE__POSTGRES__PASSWORD}
      AUTHELIA_NOTIFIER__SMTP__ADDRESS: ${AUTHELIA_NOTIFIER__SMTP__ADDRESS}
      AUTHELIA_NOTIFIER__SMTP__SENDER: ${AUTHELIA_NOTIFIER__SMTP__SENDER}
    ports: []
    networks:
      - authelia_internal
      - proxy_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://127.0.0.1:9091/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    user: "${AUTHELIA_UID}:${AUTHELIA_GID}"

  postgresql:
    image: docker.io/library/postgres:16.13@sha256:ce5c12ac6952df86affd04ade354cfcb9a0aa1171cd7912e6dbd81578a989a63
    volumes:
      - ${BASE_STACK_DATA_PATH}/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports: []
    networks:
      - authelia_internal
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: docker.io/library/redis:8@sha256:315270d166080f537bbdf1b489b603aaaa213cb55a544acfa51feb7481abb1c0
    ports: []
    networks:
      - authelia_internal
    command: ["redis-server", "--save", "", "--appendonly", "no", "--loglevel", "warning"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  authelia_internal:
    internal: true
  proxy_net:
    external: true
    name: network_backend_net
